#!/usr/bin/env python3
"""Post-lock development analyses (tune partition only): three-seed mechanism ladder and pretraining/scale controls
under the frozen complete 3-epoch schedule (last-epoch weights, no checkpoint selection). Writes
results/aggregate/table3b_multiseed_ablation.csv and paper/numbers.tex (macros used by main.tex)."""
from __future__ import annotations
import json, glob, sys
from pathlib import Path
import numpy as np, pandas as pd
ROOT = Path(__file__).resolve().parents[2]; REPO = Path(__file__).resolve().parents[1]
S = json.load(open(ROOT / "private/evaluation/380269a4a6db7334/summary.json"))
rows = []
for rd in sorted(glob.glob(str(ROOT / "private/runs/dev_*"))):
    if not Path(rd, "config.resolved.json").exists(): continue
    cfg = json.load(open(rd + "/config.resolved.json")); st = json.load(open(rd + "/status.json"))
    if cfg["epochs"] != 3 or st["status"] != "PASS": continue
    ev = [json.loads(l) for l in open(rd + "/events.jsonl")]
    rows.append({"config": cfg["config_id"], "seed": cfg["seed"], "params": cfg["parameters"]["total"], "tune_kl_last": ev[-1]["tune_patient_kl"], "tune_rowkl_last": ev[-1]["tune_row_kl"],
                 "tune_kl_best": min(e["tune_patient_kl"] for e in ev), "gate_mean": ev[-1].get("tune_gate_mean"), "wall_min": st["wall_seconds"] / 60})
t = pd.DataFrame(rows).sort_values(["config", "seed"])
agg = t.groupby("config").agg(params=("params", "first"), n_seeds=("seed", "count"), kl_mean=("tune_kl_last", "mean"), kl_sd=("tune_kl_last", "std"), rowkl_mean=("tune_rowkl_last", "mean"), best_mean=("tune_kl_best", "mean")).reset_index()
def paired(a, b):
    va = t[t.config == a].set_index("seed").tune_kl_last; vb = t[t.config == b].set_index("seed").tune_kl_last; ks = sorted(set(va.index) & set(vb.index))
    d = np.array([va[k] - vb[k] for k in ks]); return d.mean(), (d.std(ddof=1) if len(d) > 1 else np.nan), len(d), d
ladder = [("foveation", "A1", "B2"), ("gate", "A2", "A1"), ("aux", "P", "A2"), ("all", "P", "B2"), ("pretrain", "B3", "B3S"), ("width", "B3", "B3H"), ("bthreevsbtwo", "B3", "B2"), ("pvsbthree", "P", "B3"), ("scratchvsp", "B3S", "P"), ("halfvsp", "B3H", "P")]
out = []
for key, a, b in ladder:
    m, sd, n, d = paired(a, b); out.append({"comparison": f"{a} - {b}", "key": key, "mean_delta": m, "sd": sd, "n_seeds": n, "per_seed": list(np.round(d, 4))})
lad = pd.DataFrame(out)
pub = REPO / "results" / "aggregate"; t.to_csv(pub / "table3b_multiseed_runs.csv", index=False); agg.to_csv(pub / "table3b_multiseed_ablation.csv", index=False); lad.to_csv(pub / "table3b_multiseed_ladder.csv", index=False)
def f(x, p=3): return f"{x:.{p}f}"
def sgn(x, p=3): return f"{x:+.{p}f}"
mac = []
for _, r in agg.iterrows():
    k = r.config.replace("_", "").replace("1", "one").replace("2", "two").replace("3", "three")
    mac.append(f"\\newcommand{{\\kl{k}}}{{{f(r.kl_mean)}}}"); mac.append(f"\\newcommand{{\\sd{k}}}{{{f(r.kl_sd)}}}"); mac.append(f"\\newcommand{{\\n{k}}}{{{int(r.n_seeds)}}}")
for _, r in lad.iterrows():
    mac.append(f"\\newcommand{{\\d{r.key}}}{{{sgn(r.mean_delta)}}}"); mac.append(f"\\newcommand{{\\dsd{r.key}}}{{{f(r.sd)}}}")
d = pd.read_csv(ROOT / "private/figures_private/v09_per_component_delta_calibrated.csv"); sd = d.delta_kl.std(ddof=1); mde = (1.96 + 0.8416) * sd / np.sqrt(len(d))
mac += [f"\\newcommand{{\\testpairedsd}}{{{f(sd)}}}", f"\\newcommand{{\\testmde}}{{{f(mde)}}}", f"\\newcommand{{\\ntestpat}}{{{len(d)}}}"]
(REPO / "paper" / "numbers.tex").write_text("% generated by multiseed_ablation.py; do not edit\n" + "\n".join(mac) + "\n")
print(agg.round(4).to_string(index=False)); print(lad[["comparison", "mean_delta", "sd", "n_seeds", "per_seed"]].round(4).to_string(index=False)); print("macros:", len(mac))
